# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc import yematatu_pb2 as client_dot_grpc_dot_yematatu__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class YematatuStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/yematatu.Yematatu/SendMessage',
                request_serializer=client_dot_grpc_dot_yematatu__pb2.Message.SerializeToString,
                response_deserializer=client_dot_grpc_dot_yematatu__pb2.MessageResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/yematatu.Yematatu/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=client_dot_grpc_dot_yematatu__pb2.HealthCheckReponse.FromString,
                )


class YematatuServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YematatuServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=client_dot_grpc_dot_yematatu__pb2.Message.FromString,
                    response_serializer=client_dot_grpc_dot_yematatu__pb2.MessageResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=client_dot_grpc_dot_yematatu__pb2.HealthCheckReponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yematatu.Yematatu', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Yematatu(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yematatu.Yematatu/SendMessage',
            client_dot_grpc_dot_yematatu__pb2.Message.SerializeToString,
            client_dot_grpc_dot_yematatu__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yematatu.Yematatu/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            client_dot_grpc_dot_yematatu__pb2.HealthCheckReponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
