# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/grpc/yematatu.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63lient/grpc/yematatu.proto\x12\x08yematatu\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x07Message\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"4\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\"&\n\x12HealthCheckReponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\x90\x01\n\x08Yematatu\x12=\n\x0bSendMessage\x12\x11.yematatu.Message\x1a\x19.yematatu.MessageResponse\"\x00\x12\x45\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1c.yematatu.HealthCheckReponse\"\x00\x62\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_MESSAGERESPONSE = DESCRIPTOR.message_types_by_name['MessageResponse']
_HEALTHCHECKREPONSE = DESCRIPTOR.message_types_by_name['HealthCheckReponse']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'client.grpc.yematatu_pb2'
  # @@protoc_insertion_point(class_scope:yematatu.Message)
  })
_sym_db.RegisterMessage(Message)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'client.grpc.yematatu_pb2'
  # @@protoc_insertion_point(class_scope:yematatu.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)

HealthCheckReponse = _reflection.GeneratedProtocolMessageType('HealthCheckReponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKREPONSE,
  '__module__' : 'client.grpc.yematatu_pb2'
  # @@protoc_insertion_point(class_scope:yematatu.HealthCheckReponse)
  })
_sym_db.RegisterMessage(HealthCheckReponse)

_YEMATATU = DESCRIPTOR.services_by_name['Yematatu']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=69
  _MESSAGE._serialized_end=107
  _MESSAGERESPONSE._serialized_start=109
  _MESSAGERESPONSE._serialized_end=161
  _HEALTHCHECKREPONSE._serialized_start=163
  _HEALTHCHECKREPONSE._serialized_end=201
  _YEMATATU._serialized_start=204
  _YEMATATU._serialized_end=348
# @@protoc_insertion_point(module_scope)
